name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_FORK_TOKEN }}

      - name: Add Upstream repository
        run: |
          git remote add upstream https://github.com/drivendataorg/cookiecutter-data-science.git
      
      - name: Fetch Upstream repository
        run: |
          git fetch upstream
      
      - name: Merge Upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || true  # Ignore merge conflicts for now
      - name: Push changes to Fork
        run: |
          git push origin main || true  # Ignore push errors if no changes are made
      - name: Clean up
        run: |
          git remote remove upstream || true  # Clean up the remote reference
          git gc --prune=now  # Clean up unnecessary files and optimize the local repository
      - name: Notify completion
        run: |
          echo "Fork sync completed successfully."
          # Optionally, you can add a notification step here (e.g., Slack, email)
